services:
  minio:
    image: minio/minio
    environment:
      - MINIO_CONSOLE_ADDRESS=0.0.0.0:9001
    ports:
      - '9000:9000'
      - '9001:9001'
    entrypoint: ["minio", "server", "/data"]
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '15672:15672'
