[project]
name = "sqc"
version = "2023.0.0"
requires-python = ">= 3.11.6"
dependencies = [
    "loguru",
    "minio"
]

[tool.pdm.scripts]
endpoint = {call = "endpoint.main:main"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
