#+title: Bachelor thesis notes
#+author: mj

* Assignment
Mít vlastní validační server, který poběží na MetaCentru, včetně API, a porovnat
jeho výstup s výstupem validačního serveru PDB

Dílčí cíle:

Seznámit se s databází PDB, jejím validačním serverem a výstupy z něj.

Seznámit se se softwarovými nástroji tvořícími PDB validační server, jejichž
implementace nebo zdrojové kódy jsou k dispozici, s důrazem na software, který
validuje geometrii struktur Spustit tyto softwarové nástroje v prostředí
MetaCentra, a to buď na virtuálním serveru, nebo v kontejneru.

Zdokumentovat kompletní postup spuštění těchto nástrojů.

Implementovat funkcionalitu validačního serveru PDB, kterou není možné získat z
dostupné implementace nebo zdrojových kódů již existujícího software, s důrazem
na metody validace geometrie struktur.

Vytvořit API a zdokumentovat jej Porovnat výstupy z lokálního validačního
serveru s výstupem z validačního serveru PDB a provést analýzu rozdílů.

* Future workplan
** Py library that adapts Dangle, Reduce, Probe?
** Machine readable output
** Human readable output
Jinja/Asciidoc/Hugo?
** PDB output XML adapter to my output

* Current work
** DONE Spin up a docker compose with the file system
** TODO Try to create the entire system, at least in a mocking version
*** TODO Return a result for each validation

** TODO Figure out the deployment of the system
** TODO Add molprobity binaries to PATH

* Discussion points

* References
** [[file:papers/validation-of-structures-pdb.pdf][Validation of structures in PDB]]

** [[file:./papers/rna-2008-richardson.pdf][Richardson et al., 2008]]
RNA backbone: Consensus all-angle conformers and modular string nomenclature

* Model quality
** Standard geometry
Describes quality of covalent geometry for protein, DNA and RNA molecules.

*** Bond lengths and angles
Expected length and angle values for amino acids and nucleotides are available
in a wwPDB compilation (wwPDB, 2012).

[[MolProbity]]'s *Dangle* program calculates [[Z-score]]s of length and angle values for
each residue in the molecule relative to the expected values.

The root-mean-square value of the [[Z-score]]s (RMSZ) is calculated for individual
residues and averaged for each chain and over the whole molecule.

*** Chirality and planarity
Deviations from expected chirality and planarity ale calculated by
Validation-pack (Feng et al.).

**** TODO this might have to be implemented from scratch

** Too-close contacts
This section provides details about too-close contacts between pairs of atoms
that are not bonded where there is an unfavorable steric overlaps of van der
Waals shells (clashes).

*** Within assymetric unit (ASU)
*Reduce* and *Probe* programs of [[MolProbity]].

*** Symmetry-related clashes
Identified by Validation-pack

**** TODO might have to be implement from scratch

** Torsion angles
*** Protein backbone
This section only if there are protein molecules present in the entry.
Ramachandran plots calculated by [[MolProbity]]
*** Protein sidechains
[[MolProbity]] analysis of sidechains

*** RNA
Quality of RNA chains by [[MolProbity]]'s analysis of ribose sugar puckers and
rotameric nature of "suites" of backbone torsion angles (Richardson et al.,
2008, Chen et al., 2010 for details).

* Bookmarks

** Software tools
[[https://www.wwpdb.org/validation/onedep-validation-web-service-interface][OneDep validation web service interface]]
[[https://validate.wwpdb.org][PDB validation server]]

** General
[[https://www.wwpdb.org/validation/XrayValidationReportHelp][User guide to wwPDB X-ray validation reports]]

* Software tools
** MolProbity

[[file:papers/mol-probity.pdf][MolProbity: all-atom structure validation for macromolecular crystallography]]

[[https://github.com/rlabduke/MolProbity][GitHub repo]]

Is a composite of other tools. Provides a CLI interface that can be used.

** PDB-REDO/density-fitness
https://github.com/PDB-REDO/density-fitness
